# Generated by Django 5.1.4 on 2024-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="branch",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
