# Generated by Django 5.1.4 on 2024-12-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_loantype"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50)),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("loan_tenure", models.IntegerField()),
                (
                    "documents",
                    models.FileField(
                        blank=True, null=True, upload_to="loan_documents/"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="Pending", max_length=20)),
                (
                    "loan_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.loantype",
                    ),
                ),
            ],
        ),
    ]
