# Generated by Django 5.1.4 on 2024-12-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_loanapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="loan_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
