# Generated by Django 5.1.4 on 2024-12-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_loanapplication_loan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
