# Generated by Django 5.1.4 on 2024-12-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_loanapplication_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
